CREATE DATABASE IF NOT EXISTS Users;
USE Users;
CREATE TABLE IF NOT EXISTS users(
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(40) NOT NULL,
job  VARCHAR(40) NOT NULL,
age INT NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
INSERT INTO users(name, job, age)
VALUES ('Joe', 'programmer', 22)